name: build

on:
  schedule:
    - cron: 0 0 * * 5
  pull_request:
  push:
    branches:
      - master

jobs:
  build-t86-ubuntu:
    name: Build and Unit test T86
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          cd ${{ github.workspace }}/src
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Sanitizer
          make -j
      - name: Unit tests
        run: |
          cd ${{ github.workspace }}/src/build
          make test
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: t86
          path: |
            ${{ github.workspace }}/src/build/t86-cli/t86-cli
            ${{ github.workspace }}/src/build/dbg-cli/dbg-cli
          retention-days: 1
            
  test-dbg-cli-ubuntu:
    needs: [build-t86-ubuntu]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download T86
        uses: actions/download-artifact@v3
        with:
          name: t86
      - name: permissions
        run: chmod +x ${{ github.workspace }}/dbg-cli/dbg-cli
      - name: Run tests
        run: |
          cd ${{ github.workspace }}/src
          ./scripts/run_dbg_tests.sh ../dbg-cli/dbg-cli

  test-t86-cli-ubuntu:
    needs: [build-t86-ubuntu]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download dbg-cli
        uses: actions/download-artifact@v3
        with:
          name: t86
      - name: permissions
        run: chmod +x ${{ github.workspace }}/t86-cli/t86-cli
      - name: Run tests
        run: |
          cd ${{ github.workspace }}/src
          ./scripts/run_t86_tests.sh ../t86-cli/t86-cli

# =============== MacOS ===============
  build-t86-macos:
    name: Build and Unit test T86 on MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          cd ${{ github.workspace }}/src
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Sanitizer
          make -j
      - name: Unit tests
        run: |
          cd ${{ github.workspace }}/src/build
          make test

# =============== Arch Linux =============
  build-t86-arch:
    name: Build and Unit test T86 on Arch Linux
    runs-on: ubuntu-latest
    container:
      image: archlinux
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}
    steps:
      - name: Packages
        run: |
          pacman -Syu --noconfirm gcc make cmake git
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          cd ${{ github.workspace }}/src
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Sanitizer
          make -j
      - name: Unit tests
        run: |
          cd ${{ github.workspace }}/src/build
          make test
