name: build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-t86:
    name: Build and Unit test T86
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          cd ${{ github.workspace }}/t86
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Sanitizers
          make -j
      - name: Unit tests
        run: |
          cd ${{ github.workspace }}/t86/build
          make test
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: t86
          path: |
            ${{ github.workspace }}/t86/build/t86-cli/t86-cli
            ${{ github.workspace }}/t86/build/dbg-cli/dbg-cli
          retention-days: 1
            
  test-dbg-cli:
    needs: [build-t86]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download T86
        uses: actions/download-artifact@v3
        with:
          name: t86
      - name: permissions
        run: chmod +x ${{ github.workspace }}/dbg-cli/dbg-cli
      - name: Run tests
        run: |
          cd ${{ github.workspace }}/t86/dbg-cli
          ./scripts/run_tests.sh ../../dbg-cli/dbg-cli

  test-t86-cli:
    needs: [build-t86]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download dbg-cli
        uses: actions/download-artifact@v3
        with:
          name: t86
      - name: permissions
        run: chmod +x ${{ github.workspace }}/t86-cli/t86-cli
      - name: Run tests
        run: |
          cd ${{ github.workspace }}/t86
          ./scripts/run_tests.sh ../t86-cli/t86-cli
